const data_city = [
  { value: 'Casablanca' },
  { value: 'Rabat' },
  { value: 'Fes' },
  { value: 'Sale' },
  { value: 'Marrakesh' },
  { value: 'Agadir' },
  { value: 'Tangier' },
  { value: 'Meknes' },
  { value: 'Oujda-Angad' },
  { value: 'Al Hoceima' },
  { value: 'Tetouan' },
  { value: 'Temara' },
  { value: 'Safi' },
  { value: 'Mohammedia' },
  { value: 'Khouribga' },
  { value: 'Beni Mellal' },
  { value: 'Fes al Bali' },
  { value: 'El Jadid' },
  { value: 'Taza' },
  { value: 'Nador' },
  { value: 'Settat' },
  { value: 'Larache' },
  { value: 'Ksar El Kebir' },
  { value: 'Khemisset' },
  { value: 'Guelmim' },
  { value: 'Berrechid' },
  { value: 'Errachidia' },
  { value: 'Oued Zem' },
  { value: 'Al Fqih Ben Calah' },
  { value: 'Taourirt' },
  { value: 'Berkane' },
  { value: 'Sidi Slimane' },
  { value: 'Sidi Qacem' },
  { value: 'Khenifra' },
  { value: 'Ifrane' },
  { value: 'Taroudant' },
  { value: 'Essaouira' },
  { value: 'Tiflet' },
  { value: 'Oulad Teima' },
  { value: 'Sefrou' },
  { value: 'Youssoufia' },
  { value: 'Tan-Tan' },
  { value: 'Ouezzane' },
  { value: 'Guercif' },
  { value: 'Ouarzazat' },
  { value: 'Tirhanimine' },
  { value: 'Dakhla' },
  { value: 'Tiznit' },
  { value: 'Fnidek' },
  { value: 'Azrou' },
  { value: 'Midelt' },
  { value: 'Skhirate' },
  { value: 'Souq Larb' },
  { value: 'Jerada' },
  { value: 'Smara' },
  { value: 'Kasba Tadla' },
  { value: 'Sidi Bennour' },
  { value: 'Imzouren' },
  { value: 'Martil' },
  { value: 'Azemmour' },
  { value: 'Tinghir' },
  { value: 'Chefchaouene' },
  { value: 'Al Aaroui' },
  { value: 'El Aioun' },
  { value: 'Zagora' },
  { value: 'Taounate' },
  { value: 'Tirhanimine' },
  { value: 'Sidi Yahia El Gharb' },
  { value: 'Zaio' },
  { value: 'Asilah' },
  { value: 'El Hajeb' },
  { value: 'Mechraa Bel Ksiri' },
  { value: 'Bouznika' },
  { value: 'Tahla' },
  { value: 'Arfoud' },
  { value: 'Setti Fatma' },
  { value: 'Recani' },
  { value: 'Sidi Ifni' },
  { value: 'Ahfir' },
  { value: 'Oulmes' },
  { value: 'Bni Bouayach' },
  { value: 'Ain Beni Mathar' },
  { value: 'Boujniba' },
  { value: 'Kelaat Mgouna' },
  { value: 'Zawyat an Nwacer' },
  { value: 'Figuig (Centre)' },
  { value: 'Targuist' },
  { value: 'Midar' },
  { value: 'Cap Negro II' },
  { value: 'Mhamid' },
  { value: 'Gueltat Zemmour' },
  { value: 'Oualidia' },
  { value: 'Tarfaya' },
  { value: 'Ain Leuh' },
  
];

export default data_city;

