# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComingooDriverApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ComingooDriverApp

  pod 'Firebase/Core'
  pod 'Firebase/Auth', '~> 5.15.0'
  
  target 'ComingooDriverApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ComingooDriverAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ComingooDriverApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ComingooDriverApp-tvOS

end
